In [1]:
import numpy as np 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel("Online Retail.xlsx")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df.shape

(541909, 8)

In [9]:
print(df.columns.tolist())

['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [16]:
import pandas as pd

print("Original shape:", df.shape)

df = df.dropna(subset=['CustomerID', 'Description'])
print("After dropping nulls:", df.shape)

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]
print("After removing cancellations:", df.shape)

df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] > 0]
print("After removing bad quantities/prices:", df.shape)

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df['CustomerID'] = df['CustomerID'].astype(int)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print("\nFinal cleaned shape:", df.shape)
print(df.dtypes)

Original shape: (541909, 8)
After dropping nulls: (406829, 8)
After removing cancellations: (397924, 8)
After removing bad quantities/prices: (397884, 8)

Final cleaned shape: (397884, 9)
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
TotalPrice            float64
dtype: object

In [17]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("shardul@123")
engine = create_engine(f'mysql+pymysql://root:{password}@127.0.0.1:3306/ecommerce_analysis')

df.to_sql('online_retail', con=engine, if_exists='replace', index=False)
print("Data loaded successfully:", len(df), "rows")

Data loaded successfully: 397884 rows

In [18]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,14.85

In [19]:
print(df['InvoiceDate'].max())

2011-12-09 12:50:00

In [20]:
from datetime import datetime

In [21]:
# referecne date one day after the last transaction
reference_date = datetime(2012, 12, 10)

In [27]:
# calculate rfm (recencey , frequnecy , monetary)
rfm = df.groupby('CustomerID').agg(
    Recency = ('InvoiceDate' , lambda x: (reference_date - x.max()).days),
    Frequency = ('InvoiceNo' , 'nunique'),
    Monetary =('TotalPrice' , 'sum')).reset_index()

rfm['Monetary'] = rfm['Monetary'].round(2)

In [28]:
print(rfm.shape)

(4338, 4)

In [29]:
print(rfm.head(10))

   CustomerID  Recency  Frequency  Monetary
0       12346      691          1  77183.60
1       12347      368          7   4310.00
2       12348      441          4   1797.24
3       12349      384          1   1757.55
4       12350      676          1    334.40
5       12352      402          8   2506.04
6       12353      570          1     89.00
7       12354      598          1   1079.40
8       12355      580          1    459.40
9       12356      388          3   2811.43

In [30]:
# higher recency score = bought more recently
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=4 , labels=[4,3,2,1])

In [33]:
# higher Frequency Score = bought more often
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first') , q=4 , labels=[1,2,3,4])

In [34]:
# higher Monetary Score = spent more
rfm['M_score'] = pd.qcut(rfm['Monetary'].rank(method='first'), q=4 , labels=[1,2,3,4])

In [36]:
# Combine Score
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_score'].astype(str) + rfm['M_score'].astype(str)

In [38]:
print(rfm[['CustomerID', 'Recency', 'Frequency', 'Monetary', 'R_Score', 'F_score', 'M_score', 'RFM_Score']].head(10))

   CustomerID  Recency  Frequency Monetary R_Score F_score M_score RFM_Score
0       12346      691          1        4       1       1       4       114
1       12347      368          7        4       4       4       4       444
2       12348      441          4        4       2       3       4       234
3       12349      384          1        4       3       1       4       314
4       12350      676          1        2       1       1       2       112
5       12352      402          8        4       3       4       4       344
6       12353      570          1        1       1       1       1       111
7       12354      598          1        3       1       1       3       113
8       12355      580          1        2       1       1       2       112
9       12356      388          3        4       3       3       4       334

In [39]:
def assign_segment(score):
    if score in ['444', '443', '434', '344', '433']:
        return 'Champion'
    elif score in ['442', '441', '432', '431', '342', '341']:
        return 'Loyal'
    elif score in ['334', '333', '332', '331', '324', '323']:
        return 'Potential Loyalist'
    elif score in ['412', '411', '311', '312', '411']:
        return 'New Customer'
    elif score in ['244', '243', '234', '233', '144', '143']:
        return 'At Risk'
    elif score in ['111', '112', '121', '122', '211', '212']:
        return 'Lost'
    else:
        return 'Others'

rfm['Segment'] = rfm['RFM_Score'].apply(assign_segment)

In [41]:
print(rfm['Segment'].value_counts())
print("\n")

Segment
Others                1171
Lost                  1042
Champion              1006
Potential Loyalist     400
At Risk                385
New Customer           238
Loyal                   96
Name: count, dtype: int64

In [46]:
print(rfm.dtypes)

CustomerID       int64
Recency          int64
Frequency        int64
Monetary      category
R_Score          int64
Frequncy      category
F_score       category
M_score       category
RFM_Score       object
Segment         object
F_Score          int64
M_Score          int64
dtype: object

In [47]:
# drop all duplicate and category columns and start fresh
rfm = rfm[['CustomerID', 'Recency', 'Frequency', 'Monetary']].copy()

# make sure Monetary is float
rfm['Monetary'] = rfm['Monetary'].astype(float)

# recreate scores cleanly
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=4, labels=[4, 3, 2, 1]).astype(int)
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=4, labels=[1, 2, 3, 4]).astype(int)
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), q=4, labels=[1, 2, 3, 4]).astype(int)

# combine into RFM score
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

# apply segments
rfm['Segment'] = rfm['RFM_Score'].apply(assign_segment)

# verify dtypes
print(rfm.dtypes)
print("\n")

# count per segment
print(rfm['Segment'].value_counts())
print("\n")

# summary per segment
print(rfm.groupby('Segment').agg(
    Total_Customers=('CustomerID', 'count'),
    Avg_Recency=('Recency', 'mean'),
    Avg_Frequency=('Frequency', 'mean'),
    Avg_Monetary=('Monetary', 'mean')
).round(2))

CustomerID      int64
Recency         int64
Frequency       int64
Monetary      float64
R_Score         int64
F_Score         int64
M_Score         int64
RFM_Score      object
Segment        object
dtype: object


Segment
Others                1171
Lost                  1042
Champion              1006
Potential Loyalist     400
At Risk                385
New Customer           238
Loyal                   96
Name: count, dtype: int64


                    Total_Customers  Avg_Recency  Avg_Frequency  Avg_Monetary
Segment
At Risk                         385       455.43           4.95          3.45
Champion                       1006       378.28          10.96          3.76
Lost                           1042       581.52           1.12          1.39
Loyal                            96       375.61           3.29          1.78
New Customer                    238       392.34           1.00          1.40
Others                         1171       458.46           2.28          2.25
Potential Loyalist              400       397.36           3.03          2.89

In [48]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# save to CSV for Tableau
rfm.to_csv('rfm_segments.csv', index=False)
print("CSV saved!")

# save to MySQL
password = quote_plus("shardul@123")
engine = create_engine(f'mysql+pymysql://root:{password}@127.0.0.1:3306/ecommerce_analysis')
rfm.to_sql('rfm_segments', con=engine, if_exists='replace', index=False)
print("Saved to MySQL:", len(rfm), "customers")

CSV saved!
Saved to MySQL: 4338 customers

In [49]:
rfm.to_csv(r'D:\Onlone Retail Analysis\rfm_segments.csv', index=False)
print("Saved!")

Saved!

In [51]:
import pandas as pd
top_products = pd.read_csv(r'D:\Onlone Retail Analysis\best_selling_product.csv')
print(top_products.head())
print(top_products.columns.tolist())

   total_revenue  total_units_sold
0      168469.60             80995
1       81416.73             77916
2       13586.25             54415
3       85220.78             46181
4      100448.15             36725
['total_revenue', 'total_units_sold']

In [52]:
top_products = df.groupby('Description').agg(
    total_units_sold=('Quantity', 'sum'),
    total_revenue=('TotalPrice', 'sum')
).round(2).reset_index()

# sort by revenue and take top 10
top_products = top_products.sort_values('total_revenue', ascending=False).head(10)

print(top_products)

# save again
top_products.to_csv(r'D:\Onlone Retail Analysis\best_selling_product.csv', index=False)
print("Saved!")

                             Description  total_units_sold  total_revenue
2319         PAPER CRAFT , LITTLE BIRDIE             80995      168469.60
2767            REGENCY CAKESTAND 3 TIER             12402      142592.95
3698  WHITE HANGING HEART T-LIGHT HOLDER             36725      100448.15
1762             JUMBO BAG RED RETROSPOT             46181       85220.78
1992      MEDIUM CERAMIC TOP STORAGE JAR             77916       81416.73
2611                             POSTAGE              3120       77803.96
2345                       PARTY BUNTING             15291       68844.33
216        ASSORTED COLOUR BIRD ORNAMENT             35362       56580.34
2130                              Manual              7173       53779.93
2656                  RABBIT NIGHT LIGHT             27202       51346.20
Saved!